"""empty message

Revision ID: a9d4be17691e
Revises: dd2ad73427aa
Create Date: 2021-09-08 18:28:03.512168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d4be17691e'
down_revision = 'dd2ad73427aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
